kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g
kotlin.js.ir.output.granularity=whole-program

kotlin.js.yarn=true

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g

group=io.github.hansanto
description=Tools to interact with Vault
# x-release-please-start-version
version=0.0.0
# x-release-please-end-version
