package io.github.hansanto.vaulttools.shared

fun interface BrowserLauncher {
    /**
     * Open the given URL in the user's default browser.
     * This is used to open the OIDC authentication URL for the user to authenticate.
     *
     * @param url The provider URL to open in the browser for user authentication. This URL is generated by Vault and contains the necessary parameters for the OIDC flow.
     * @return `true` if the Browser was successfully opened, `false` otherwise.
     * Note that a successful opening does not guarantee that the user will complete the authentication process, but it indicates that the URL was successfully launched in the browser.
     */
    suspend fun open(url: String): Boolean
}

/**
 * Default implementation of [BrowserLauncher] that uses platform-specific logic to open the default web browser with the provided URL.
 */
object DefaultBrowserLauncher : BrowserLauncher {
    override suspend fun open(url: String): Boolean = openBrowser(url)
}

/**
 * Opens the default web browser with the specified URL.
 *
 * @param url The URL to open in the browser.
 * @return True if the browser was successfully opened, false otherwise.
 */
expect suspend fun openBrowser(url: String): Boolean
