name: build

on:
  push:
    branches-ignore:
      - "v*" # Skip tags
  workflow_dispatch:
    inputs:
      upload-report:
        type: boolean
        description: 'Upload the test report'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-wrapper:
    uses: ./.github/workflows/gradle-validation.yml

  build:
    needs: [ validate-wrapper ]
    runs-on: ubuntu-26.04
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🙈 Get gradle dependencies
        id: restore-cache-gradle
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle', '**/build.gradle.kts', '**/settings.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: ⚙️ Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          java-version-file: .sdkmanrc

      - name: 🧹 Check format
        run: ./gradlew ktlintCheck

      - name: 🧹 Check code style
        run: ./gradlew detektAll

      - name: 🛠 Build
        run: ./gradlew kotlinNpmInstall && ./gradlew assemble

      - name: 🙈 Save gradle dependencies
        if: always() && steps.restore-cache-gradle.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle', '**/build.gradle.kts', '**/settings.gradle.kts', '**/gradle-wrapper.properties') }}
