name: gradle-validation

on:
  workflow_call:

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6

      - name: ✅ Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5
